spring.application.name=alunmos
spring.datasource.url=jdbc:mysql://localhost:3306/alumnost
spring.datasource.username=root
spring.datasource.password=ortiz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true